//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mmixide.rc
//
#define IDR_MENU                        104
#define IDR_ACCELERATOR                 106
#define IDI_ICON                        107
#define IDB_FILE_NEW                    108
#define IDI_FILE_NEW                    110
#define IDI_VIEW_ZOOMOUT                111
#define IDI_FILE_OPEN                   112
#define IDI_FILE_SAVE                   113
#define IDI_EDIT_COPY                   114
#define IDI_EDIT_CUT                    115
#define IDI_EDIT_PASTE                  116
#define IDI_EDIT_REDO                   117
#define IDI_EDIT_UNDO                   118
#define IDI_HELP                        119
#define IDI_MMIX_DEBUG                  120
#define IDI_VIEW_ZOOMIN                 121
#define IDD_SHOW_SPECIAL                127
#define IDD_SHOW_DEBUG                  128
#define IDD_FIND                        129
#define IDD_OPTIONS_ASSEMBLER           130
#define IDD_OPTIONS_EDITOR              131
#define IDI_FINDREPLACE                 132
#define IDI_DEBUG_STEP                  134
#define IDI_DEBUG_CONTINUE              136
#define IDI_DEBUG_PAUSE                 138
#define IDI_DEBUG_HALT                  139
#define IDD_OPTIONS_SYMTAB              141
#define IDD_OPTIONS_SOURCES             142
#define IDC_SHOW_LOCAL                  1001
#define IDC_SHOW_RA                     1001
#define IDC_SHOW_GLOBAL                 1002
#define IDC_SHOW_RB                     1002
#define IDC_SHOW_SPECIAL                1003
#define IDC_SHOW_RC                     1003
#define IDC_COMBO1                      1003
#define IDC_COMBO_FIND                  1003
#define IDC_SHOW_REGSTACK               1004
#define IDC_SHOW_RD                     1004
#define IDC_FIND_NEXT                   1004
#define IDC_SHOW_TEXT                   1005
#define IDC_SHOW_RE                     1005
#define IDC_FIND_PREV                   1005
#define IDC_SHOW_DATA                   1006
#define IDC_SHOW_RF                     1006
#define IDC_CHECK_CASE                  1006
#define IDC_SHOW_POOL                   1007
#define IDC_SHOW_RG                     1007
#define IDC_CHECK_WORD                  1007
#define IDC_SHOW_STACK                  1008
#define IDC_SHOW_RH                     1008
#define IDC_COMBO_REPLACE               1008
#define IDC_SHOW_NEG                    1009
#define IDC_SHOW_RI                     1009
#define IDC_REPLACE                     1009
#define IDC_SHOW_RJ                     1010
#define IDC_CHECK_MAIN                  1010
#define IDC_SHOW_RK                     1011
#define IDC_REPLACE_ALL                 1011
#define IDC_CHECK_AUTOSAVE              1011
#define IDC_CHECK_TRACE                 1011
#define IDC_SHOW_RL                     1012
#define IDC_CHECK_LINENO                1012
#define IDC_SPIN_BUFFERSIZE             1012
#define IDC_SHOW_RM                     1013
#define IDC_CHECK_WRAP                  1013
#define IDC_BUFFERSIZE                  1013
#define IDC_CHECK_PROFILE               1013
#define IDC_CHECK_EXCEPTIONS            1013
#define IDC_SHOW_RN                     1014
#define IDC_CHECK_X                     1014
#define IDC_SHOW_RO                     1015
#define IDC_CHECK_LISTING               1015
#define IDC_SHOW_RP                     1016
#define IDC_SELECT_SPECIALS             1016
#define IDC_SHOW_RQ                     1017
#define IDC_CHECK_OS                    1017
#define IDC_SHOW_RR                     1018
#define IDC_CHECK_LOCALS                1018
#define IDC_SHOW_RS                     1019
#define IDC_CHECK_REGISTERS             1019
#define IDC_SHOW_RT                     1020
#define IDC_CHECK_SMALL                 1020
#define IDC_TABWIDTH                    1020
#define IDC_SHOW_RU                     1021
#define IDC_SPIN_TABWIDTH               1021
#define IDC_SHOW_RV                     1022
#define IDC_RADIO_BREAK_AFTER           1022
#define IDC_SHOW_RW                     1023
#define IDC_RADIO_BREAK_BEFORE          1023
#define IDC_SHOW_RX                     1024
#define IDC_LIST_FILES                  1024
#define IDC_SHOW_RY                     1025
#define IDC_ADD                         1025
#define IDC_SHOW_RZ                     1026
#define IDC_BUTTON2                     1026
#define IDC_REMOVE                      1026
#define IDC_SHOW_RBB                    1027
#define IDC_SHOW_RTT                    1028
#define IDC_SHOW_RWW                    1029
#define IDC_SHOW_RXX                    1030
#define IDC_SHOW_RYY                    1031
#define IDC_SHOW_RZZ                    1032
#define ID_FILE_EXIT                    40002
#define ID_MMIX_RUN                     40004
#define ID_HELP_ABOUT                   40014
#define ID_VIEW_MEMMORY                 40015
#define ID_VIEW_REGISTERS               40016
#define ID_REGISTERS_LOCAL              40017
#define ID_REGISTERS_GLOBAL             40018
#define ID_REGISTERS_SPECIAL            40019
#define ID_REGISTERS_STACK              40020
#define ID_OPTIONS_SPECIALREGISTERS     40021
#define ID_OPTIONS_SPECIALS             40022
#define ID_VIEW_MEMORY                  40023
#define ID_VIEW_MEM                     40024
#define ID_MEM_TEXTSEGMENT              40025
#define ID_MEM_DATASEGMENT              40026
#define ID_MEMORY_POOLSEGMENT           40027
#define ID_MEMORY_STACKSEGMENT          40028
#define ID_MEMORY_NEGATIVESEGMENT       40029
#define ID_MEM_POOLSEGMENT              40030
#define ID_MEM_STACKSEGMENT             40031
#define ID_MEM_NEGATIVESEGMENT          40032
#define ID_FILE_NEW40035                40035
#define ID_FILE_SAVE40036               40036
#define ID_FILE_SAVEAS                  40037
#define ID_EDIT_CUT40038                40038
#define ID_EDIT_COPY40039               40039
#define ID_EDIT_PASTE40040              40040
#define ID_EDIT_UNDO40041               40041
#define ID_EDIT_REDO40042               40042
#define ID_EDIT_DELETE                  40043
#define ID_EDIT_SELECTALL               40044
#define ID_EDIT_FINDANDREPLACE          40045
#define ID_EDIT_REPLACE40046            40046
#define ID_MMIX_ASSEMBLE                40047
#define ID_MMIX_DEBUG                   40048
#define ID_VIEW_ZOOMIN                  40049
#define ID_VIEW_ZOOMOUT                 40050
#define ID_FILE_PRINT40051              40051
#define ID_MMIX_CONNECT                 40052
#define ID_OPTIONS_DEBUG                40053
#define ID_VIEW_SHOWWHITESPACE          40059
#define ID_VIEW_WHITESPACE              40060
#define ID_MMIX_STOP                    40061
#define ID_VIEW_SYNTAXHIGHLIGHTING      40062
#define ID_VIEW_SYNTAX                  40063
#define ID_EDIT_FINDAGAIN               40064
#define ID_EDIT_REPLACEAGAIN            40069
#define ID_FILE_PAGESETUP               40073
#define ID_VIEW_FILELIST                40074
#define ID_VIEW_SYMBOLTABLE             40075
#define ID_OPTIONS_ASSEMBLER            40076
#define ID_OPTIONS_EDITOR               40077
#define ID_OPTIONS_MOTHERBOARD          40078
#define ID_MMIX_STEP                    40082
#define ID_MMIX_CONTINUE                40083
#define ID_MMIX_QUIT                    40084
#define ID_OPTIONS_VMB                  40085
#define ID_OPTIONS_SYMBOLTABLE          40086
#define ID_OPTIONS_SYMTAB               40087
#define ID_OPTIONS_EXTRASOURCES         40088
#define ID_OPTIONS_SOURCES              40089

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         40090
#define _APS_NEXT_CONTROL_VALUE         1027
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
