#ifndef MSPIO
#define MSPIO

#include "option.h"
#include "param.h"
#include "vmb.h"

// Define INTERRUPTS if interrupts 
// should be generated by this device (P1/P2 ports of MSP430)
#define INTERRUPTS		

// device registers
enum reg_names {
	REG_IN,		// input buffer
	REG_OUT,	// output buffer
	REG_DIR,	// direction bits (0: input, 1: output)
#ifdef INTERRUPTS
	REG_INT_FLAG,			// interrupt flags
	REG_INT_EDGE_SELECT,	//  edge selection for interrupt generation (0: interrupt on low->high transition,
							// 1: interrupt on high->low transition)
	REG_INT_ENABLE,			// interrupt enable reg (1: enable interrupts)
#endif
	REG_PORT_SELECT			// port select register: (0: I/O used for pin, 1: peripheral used for pin)
};


// The memory mapped registers allocate 4/7 bytes
#ifdef INTERRUPTS
#define MEMSIZE 7
#else
#define MEMSIZE 4
#endif

// The address of the device where the output will be sent to
extern uint64_t output_address;

// vmb reference
extern device_info vmb;

// The size of mapped memory
extern int memsize;
#endif